dist: trusty
sudo: require

os: linux

language: cpp
compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get libboost-all-dev
  - sudo apt-get install libdeal.ii-dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

after_success: 
  - codecov